/// Inline replacement for the former `warp_graphql_schema` crate (Phase 3.x).
/// The schema.graphql lives at crates/graphql/schema/schema.graphql and is
/// loaded by build.rs via `cynic_codegen::register_schema`.
#[cynic::schema("warp-server")]
pub mod schema {}

pub mod ai;
pub mod billing;
pub mod error;
pub mod experiment;
pub mod folder;
pub mod full_source_code_embedding;
pub mod generic_string_object;
pub mod mcp_gallery_template;
pub mod mutations;
pub mod notebook;
pub mod object;
pub mod object_actions;
pub mod object_permissions;
pub mod queries;
pub mod request_context;
pub mod response_context;
pub mod subscriptions;
pub mod user;
pub mod workflow;
pub mod workspace;

// Re-export the schema that's generated by the schema crate.

use cynic::impl_scalar;
impl_scalar!(crate::scalars::Time, schema::Time);
