#!/usr/bin/env bash

OS_TYPE="$(uname -s)"
PLATFORM_ARGS=()

for arg in "$@"; do
  case "${arg}" in
    -h|--help)
      echo "Usage: ./script/bootstrap [--skip-gcloud-auth]"
      exit 0
      ;;
    --skip-gcloud-auth)
      export WARP_SKIP_GCLOUD_AUTH=1
      ;;
    *)
      echo "error: unknown argument '${arg}'" >&2
      echo "Run ./script/bootstrap --help to see available options." >&2
      exit 1
      ;;
  esac
done

if [[ "$OS_TYPE" = "Darwin" ]]; then
  ./script/macos/bootstrap "${PLATFORM_ARGS[@]}"
elif [[ "$OS_TYPE" = "Linux" ]]; then
  ./script/linux/bootstrap "${PLATFORM_ARGS[@]}"
elif [[ "$OS_TYPE" =~ ^[MINGW64_NT|MSYS_NT] ]]; then
  ./script/windows/bootstrap.ps1 "${PLATFORM_ARGS[@]}"
else
  echo "No bootstrap script defined for the current platform!"
  exit 1
fi
